"""baseline_legacy_schema

Revision ID: 3f79787c9fea
Revises: 
Create Date: 2026-07-27 01:26:31.979833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f79787c9fea'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('daily_menus_menu_date_key'), 'daily_menus', type_='unique')
    op.create_index(op.f('ix_daily_menus_menu_date'), 'daily_menus', ['menu_date'], unique=True)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_daily_menus_menu_date'), table_name='daily_menus')
    op.create_unique_constraint(op.f('daily_menus_menu_date_key'), 'daily_menus', ['menu_date'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
